In [1]:
from itertools import permutations
import numpy as np
from numpy.linalg import det

# Generate all permutations of the array with four 0s and five 1s
all_permutations_3x3 = set(permutations([-1, -1, -1, -1, -1, 1, 1, 1, 1]))

# Convert each permutation into a 3x3 matrix and calculate its determinant
matrices_with_determinants_3x3 = []

for perm in all_permutations_3x3:
    matrix = np.array(perm).reshape(3, 3)
    determinant = det(matrix)

    matrices_with_determinants_3x3.append((matrix, determinant))


print(f"Number of unique matrices: {len(matrices_with_determinants_3x3)}")


for matrix, determinant in matrices_with_determinants_3x3:
    print("Matrix:\n", matrix)
    print("Determinant:", determinant)
    print() 

Number of unique matrices: 126
Matrix:
 [[ 1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]]
Determinant: 4.0

Matrix:
 [[-1 -1 -1]
 [-1  1  1]
 [-1  1  1]]
Determinant: 0.0

Matrix:
 [[ 1 -1 -1]
 [-1  1 -1]
 [-1  1  1]]
Determinant: 0.0

Matrix:
 [[-1 -1  1]
 [-1  1  1]
 [-1 -1  1]]
Determinant: 0.0

Matrix:
 [[-1  1 -1]
 [ 1 -1 -1]
 [ 1  1 -1]]
Determinant: -4.0

Matrix:
 [[-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]
Determinant: -4.0

Matrix:
 [[-1 -1  1]
 [ 1 -1  1]
 [ 1 -1 -1]]
Determinant: -4.0

Matrix:
 [[ 1  1 -1]
 [-1 -1 -1]
 [ 1  1 -1]]
Determinant: 0.0

Matrix:
 [[-1  1  1]
 [ 1 -1 -1]
 [-1  1 -1]]
Determinant: 0.0

Matrix:
 [[-1 -1  1]
 [-1 -1  1]
 [ 1 -1  1]]
Determinant: 0.0

Matrix:
 [[-1  1 -1]
 [-1 -1  1]
 [ 1  1 -1]]
Determinant: 0.0

Matrix:
 [[-1 -1  1]
 [-1  1 -1]
 [-1  1  1]]
Determinant: -4.0

Matrix:
 [[-1 -1  1]
 [-1  1  1]
 [ 1 -1 -1]]
Determinant: 0.0

Matrix:
 [[ 1 -1 -1]
 [-1  1  1]
 [-1  1 -1]]
Determinant: 0.0

Matrix:
 [[-1  1 -1]
 [ 1  1 -1]
 [-1  1 -1]]
Determinant: 0.0

Matri

In [2]:
from itertools import permutations
import numpy as np

def count_matrices_with_zero_determinant_five_zeros():
    # Generate all permutations of five 0s and four 1s for the 3x3 matrix
    all_permutations = set(permutations([-1, -1, -1, -1, -1, 1, 1, 1, 1]))
    zero_det_count = 0

    for perm in all_permutations:
        # Construct the matrix from the permutation
        matrix = np.array(perm).reshape(3, 3)
        # Calculate the determinant
        if np.linalg.det(matrix) == 0:
            zero_det_count += 1

    return zero_det_count

# Calculate the number of matrices with a determinant of 0 using five 0s and four 1s
matrices_with_zero_det_five_zeros = count_matrices_with_zero_determinant_five_zeros()
print(matrices_with_zero_det_five_zeros)


90
