In [6]:
import numpy as np
from itertools import permutations
from numpy.linalg import det

def generate_matrices_and_determinants():
    # Generate all permutations of the array with two 0s and two 1s
    all_permutations = set(permutations([0, 0, 1, 1]))

    # Convert each permutation into a 2x2 matrix and calculate its determinant
    for perm in all_permutations:
        matrix = np.array(perm).reshape(2, 2)
        determinant = det(matrix)
        print("Matrix:\n", matrix)
        print("Determinant:", determinant)
        print("---")

generate_matrices_and_determinants()


Matrix:
 [[0 1]
 [0 1]]
Determinant: 0.0
---
Matrix:
 [[1 1]
 [0 0]]
Determinant: 0.0
---
Matrix:
 [[0 1]
 [1 0]]
Determinant: -1.0
---
Matrix:
 [[1 0]
 [1 0]]
Determinant: 0.0
---
Matrix:
 [[1 0]
 [0 1]]
Determinant: 1.0
---
Matrix:
 [[0 0]
 [1 1]]
Determinant: 0.0
---
