In [1]:
from itertools import permutations
import numpy as np
from numpy.linalg import det

# Generate all permutations of the array with four 0s and five 1s
all_permutations_3x3 = set(permutations([0, 0, 0, 0, 1, 1, 1, 1, 1]))

# Convert each permutation into a 3x3 matrix and calculate its determinant
matrices_with_determinants_3x3 = []

for perm in all_permutations_3x3:
    matrix = np.array(perm).reshape(3, 3)
    determinant = det(matrix)

    matrices_with_determinants_3x3.append((matrix, determinant))


print(f"Number of unique matrices: {len(matrices_with_determinants_3x3)}")


for matrix, determinant in matrices_with_determinants_3x3:
    print("Matrix:\n", matrix)
    print("Determinant:", determinant)
    print() 

Number of unique matrices: 126
Matrix:
 [[0 0 1]
 [1 1 0]
 [1 0 1]]
Determinant: -1.0

Matrix:
 [[1 1 1]
 [1 1 0]
 [0 0 0]]
Determinant: 0.0

Matrix:
 [[0 0 1]
 [1 1 0]
 [1 1 0]]
Determinant: 0.0

Matrix:
 [[0 0 0]
 [1 1 0]
 [1 1 1]]
Determinant: 0.0

Matrix:
 [[0 1 0]
 [1 1 0]
 [1 1 0]]
Determinant: 0.0

Matrix:
 [[1 1 0]
 [0 0 0]
 [1 1 1]]
Determinant: 0.0

Matrix:
 [[1 1 0]
 [1 0 1]
 [1 0 0]]
Determinant: 1.0

Matrix:
 [[1 1 1]
 [1 0 0]
 [0 0 1]]
Determinant: -1.0

Matrix:
 [[0 1 0]
 [1 1 0]
 [1 0 1]]
Determinant: -1.0

Matrix:
 [[0 0 0]
 [1 1 1]
 [1 0 1]]
Determinant: 0.0

Matrix:
 [[1 0 0]
 [0 0 1]
 [1 1 1]]
Determinant: -1.0

Matrix:
 [[0 0 0]
 [1 1 1]
 [1 1 0]]
Determinant: 0.0

Matrix:
 [[0 1 1]
 [1 1 1]
 [0 0 0]]
Determinant: 0.0

Matrix:
 [[1 1 1]
 [0 1 0]
 [0 0 1]]
Determinant: 1.0

Matrix:
 [[1 1 1]
 [0 1 0]
 [0 1 0]]
Determinant: 0.0

Matrix:
 [[1 0 1]
 [0 1 1]
 [0 1 0]]
Determinant: -1.0

Matrix:
 [[1 0 1]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0

Matrix:
 [[0 1 1]
 [1 0 1]
 [